joint_limits:
  d1_joint_0:
    has_velocity_limits: true
    max_velocity: 1.05
    has_acceleration_limits: true
    max_acceleration: 0.5
  d1_joint_1:
    has_velocity_limits: true
    max_velocity: 1.05
    has_acceleration_limits: true
    max_acceleration: 0.5
  d1_joint_2:
    has_velocity_limits: true
    max_velocity: 1.05
    has_acceleration_limits: true
    max_acceleration: 0.5
  d1_joint_3:
    has_velocity_limits: true
    max_velocity: 1.73
    has_acceleration_limits: true
    max_acceleration: 0.75
  d1_joint_4:
    has_velocity_limits: true
    max_velocity: 1.73
    has_acceleration_limits: true
    max_acceleration: 0.75
  d1_joint_5:
    has_velocity_limits: true
    max_velocity: 1.73
    has_acceleration_limits: true
    max_acceleration: 0.75
  d1_gripper_joint:
    has_velocity_limits: true
    max_velocity: 0.02
    has_acceleration_limits: false
